on:
  push:
    paths:
      - 'docs/**'
  workflow_dispatch:

name: CreatePDFs

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pandoc and LaTeX
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra
    - name: Convert markdown to PDF
      run: |
        mkdir -p tmp
        for file in docs/*.md; do
          filename=$(basename "$file" .md)
          pandoc "$file" -o "tmp/$filename.pdf" --pdf-engine=pdflatex
        done
    - uses: actions/upload-artifact@v4
      with:
        name: platform-architecture-docs
        path: tmp
